social_media_app/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_view
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

social_media_app/social_media_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='index'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
]

social_media_app/accounts/models.py
from django.db import models
from django.contrib import auth


class User(auth.models.User, auth.models.PermissionsMixin):
    def __str__(self):
        return "@{}.".format(self.username)

social_media_app/groups/models.py
from django.db import models
from django.utils.text import slugify

from django.contrib.auth import get_user_model
User = get_user_model()
from django import template
register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='membership', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

social_media_app/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('post:single', kwargs={'username':self.user.username, 'pk':self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']

social_media_app/accounts/forms.py
from django.contrib.auth import get_user_model

from django.contrib.auth.forms import UserCreationForm

class UserSignInForm(UserCreationForm):

    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = "Email Address"

social_media_app/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import UserSignInForm


class SignUp(CreateView):
    form_class = UserSignInForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

social_media_app/groups/views.py
from django.shortcuts import render

# Create your views here.

social_media_app/posts/views.py
from django.shortcuts import render

# Create your views here.

social_media_app/social_media_app/views.py
from django.views.generic import TemplateView


class TestPage(TemplateView):
    template_name = 'accounts/test.html'


class ThanksPage(TemplateView):
    template_name = 'accounts/thanks.html'


class HomeView(TemplateView):
    template_name = 'accounts/index.html'

social_media_app/accounts/templates/accounts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Astro Social</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Bacasime+Antique&family=Montserrat:wght@100;200;300;400;500;600;700;800;900&family=Mooli&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'accounts/css/master.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Astro Social</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Groups</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Create Group</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">Log Out</a>
        </li>

      {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Groups</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Log In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:signup' %}">Sign In</a>
        </li>
      {% endif %}
    </ul>
    </div>
  </div>
</nav>
    <div class="container">
            {% block content %}
            {% endblock %}
    </div>

</body>
</html>

social_media_app/accounts/templates/accounts/index.html
{% extends "accounts/base.html" %}

{% block content %}

<h1>Witam Witam</h1>

{% endblock %}

social_media_app/accounts/templates/accounts/login.html
{% extends "accounts/base.html" %}
{% block content %}

<div class="container">
    <h1>Log In</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="Log In">
    </form>
</div>


{% endblock %}

social_media_app/accounts/templates/accounts/signup.html
{% extends "accounts/base.html" %}
{% block content %}

<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="Sign Up">
    </form>
</div>

{% endblock %}

social_media_app/accounts/templates/accounts/test.html
{% extends "accounts/base.html" %}

{% block content %}

<h1>Test</h1>

{% endblock %}

social_media_app/accounts/templates/accounts/thanks.html
{% extends "accounts/base.html" %}

{% block content %}

<h1>Thanks for visiting, come back soon</h1>

{% endblock %}

social_media_app/groups/templates/groups/group_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

social_media_app/groups/templates/groups/group_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

social_media_app/groups/templates/groups/group_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

social_media_app/groups/templates/groups/group_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

social_media_app/posts/templates/post/_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

social_media_app/posts/templates/post/post_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

social_media_app/posts/templates/post/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

social_media_app/posts/templates/post/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

social_media_app/posts/templates/post/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

social_media_app/posts/templates/post/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

social_media_app/posts/templates/post/user_post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>